Update build-oneplus-13-v13.yml

diff --git a/.github/workflows/build-oneplus-13-v13.yml b/.github/workflows/build-oneplus-13-v13.yml
--- a/.github/workflows/build-oneplus-13-v13.yml
+++ b/.github/workflows/build-oneplus-13-v13.yml
@@ -269,15 +269,13 @@ jobs:
             echo "ADIOS files integrated into source tree."
             cd $GITHUB_WORKSPACE/kernel_workspace
           fi
-          if ${{ inputs.enable_le9uo }}; then
+           if ${{ inputs.enable_le9uo }}; then
             echo "Applying EXPERIMENTAL le9 Unofficial patchset..."
             git clone https://github.com/firelzrd/le9uo.git ./le9uo_temp --depth=1
-            echo "--- Listing contents of le9uo_temp ---"
-            ls -l $GITHUB_WORKSPACE/kernel_workspace/le9uo_temp/
             cd ./kernel_platform/common
-            for patch_file in $(find "$GITHUB_WORKSPACE/kernel_workspace/le9uo_temp/le9uo_patches"  -maxdepth 1 -type f -name "*.patch" | sort -V); do
+            for patch_file in $(find "$GITHUB_WORKSPACE/kernel_workspace/le9uo_temp/le9uo_patches" -maxdepth 1 -type f -name "*.patch" | sort -V); do
               echo "Applying patch: $(basename "$patch_file")"
-              patch -p1 < "$patch_file" || echo "WARN: Could not apply patch $(basename "$patch_file") cleanly."
+              patch -p1 -F 3 < "$patch_file" || echo "WARN: Could not apply patch $(basename "$patch_file") cleanly."
             done
             rm -rf $GITHUB_WORKSPACE/kernel_workspace/le9uo_temp
             echo "le9 Unofficial patchset applied."
